version: '3'

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/var/task/bin
      - AWS_BUCKET_NAME='YOUR_BUCKET_NAME'
      - AWS_ACCESS_KEY_ID='YOUR_ACCESS_KEY_ID'
      - AWS_SECRET_ACCESS_KEY='+YOUR_SECRET_ACCESS_KEY'
    volumes:
      - ./src/:/var/task/src/
