version: '3'

services:
  lambda:
    build: .
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/var/task/bin
      - AWS_BUCKET_NAME='epicreservations'
      - AWS_ACCESS_KEY_ID='your access key id'
      - AWS_SECRET_ACCESS_KEY='your access key'
    volumes:
      - ./src/:/var/task/src/
